def menu():
    print('Welcome to Facial recognizer')
    print('=============================================')
    print('1. See Database')
    print('2. Insert New Person')
    print('3. Update New Person')
    print('4. Delete New Person')
    print('5. Train')
    print('6. Face Recognition')
    print('10. Exit')
